#include <iostream>
 
using namespace std;
 
void main()
 {
    
    cout << "Size of a Character (char) = " << sizeof(char) << " bytes" << endl;
    cout << "Size of an Integer (int) = " << sizeof(int) << " bytes" << endl;
    cout << "Size of a Floating Point (float) = " << sizeof(float) << " bytes" << endl;
    cout << "Size of Double (double) = " << sizeof(double) << " bytes" << endl;
 
   
}